### ISSUE TITLE
releasing from Travis

### ISSUE THREAD

**Issue by pepegar** [higherkindness/droste#101]
It would be great to have automatic releases from Travis.  I've integrated https://github.com/olafurpg/sbt-ci-release for https://github.com/pepegar/hammock and it's super cool.

With sbt-ci-release we get:
- automatic releases on Travis
- publication of snapshots on all merges to master
- publication of release on tag push

I'd volunteer for this one, but  I don't have publish permissions for `io.higherkindness`.

**Comment by andyscott** [comment]
👍 from me on this one.

**Comment by juanpedromoreno** [comment]
Done  👍
