### ISSUE TITLE
Basis instance for cats.free.Free

### ISSUE THREAD

**Issue by txsmith** [higherkindness/droste#102]
Hi there!

I have a use-case requiring an instance of `Basis` for `cats.free.Free`. I see that one for `Cofree` is already included (#28). Would you welcome a PR adding an instance for `Free`?

**Comment by pepegar** [comment]
I believe that we can't provide a `Project` instance for `Free`, can we? that's what's blocking us from providing the `Basis` instance for it.

In a `Free[F, A]` structure, you don't have `A` values in all nodes, just in some of them.

**Comment by txsmith** [comment]
I was under the impression that this is possible since `recursion-schemes` has instances for both `Recursive` and `Corecursive` on `Free`. (See [here](https://www.stackage.org/haddock/lts-13.8/recursion-schemes-5.1.1/Data-Functor-Foldable.html#t:Corecursive) and [here](https://www.stackage.org/haddock/lts-13.8/recursion-schemes-5.1.1/Data-Functor-Foldable.html#t:Recursive))

The instance would be for `Basis[CoattrF[F, A, ?], Free[F, A]]` since CoattrF is the base functor for Free. The `Project` instance would then map the `Pure[A]` case to the `Left[A]` of CoattrF, and the `F[Free[F,A]]` case to the `Right` of CoattrF.

**Comment by txsmith** [comment]
This is what it would potentially look like:
```scala
implicit def drosteBasisForCatsFree[F[_]: Functor, A]: Basis[CoattrF[F, A, ?], Free[F, A]] =
  Basis.Default[CoattrF[F, A, ?], Free[F, A]](
    Algebra { CoattrF.un(_).fold(Free.pure, Free.roll) },
    Coalgebra { _.fold[CoattrF[F, A, Free[F,A]]](CoattrF.pure, CoattrF.roll) }
  )
```

**Comment by pepegar** [comment]
hm, I didn't know that, I'm OK with it if it's lawful!
