### ISSUE TITLE
build for scala 2.13

### ISSUE THREAD

**Issue by chenharryhua** [higherkindness/droste#119]
it would be wonderful if there is a preview build for scala 2.13

**Comment by rajit-iov42** [comment]
@andyscott Are there any known obstacles to building and running droste with Scala 2.13? I see that artifacts for `2.13.0-M4` were published at the end of last year but I can't find something more recent.

**Comment by travisbrown** [comment]
2.13 support is [now in master](https://github.com/higherkindness/droste/pull/134), but not yet published.

**Comment by chenharryhua** [comment]
Thanks, @travisbrown. Please feel free to close this issue.

**Comment by rajit-iov42** [comment]
Perhaps when it's published?
