### ISSUE TITLE
Cross compile with Scala 3

### ISSUE THREAD

**Issue by lenguyenthanh** [higherkindness/droste#296]
Hi is there any plan to cross compile with Scala 3? Thanks!

**Comment by juanpedromoreno** [comment]
Hey @lenguyenthanh , the latest versions of droste are already cross-compiling with Scala 3 ;) . Also, this morning, I made a new release with the latest dependency updates: https://github.com/higherkindness/droste/releases/tag/v0.9.0

**Comment by lenguyenthanh** [comment]
oh, sorry didn't notice that. Thanks!
